### PR TITLE
languages cleanup

### LINKED ISSUE #170: languages cleanup
- [ ] cleanup DB fields
  - [x] remove all old/untranslated fields from DB
  - [ ] adapt webapp, should only use the translated version @eins78 
  - [x] adapt admin-webapp, should only use the translated version
  - [x] only API should still offer the old field (but dynamic/according the settings.default_lang)
- [x] remove params from API
- [x] check handling of default values in DB/seeds/…
- [x] integration test 
   - [x] default settings (default lang is active as long as a user has not selected one)
   - [x] changing the language shows different labels/etc
   - [x] changes to translations in the admin UI are reflected in all other apps (api/webapp)
     - api: vocabularies, metakeys
     - webapp: vocabularies + metakeys (public pages), contextkeys: in edit form (look in existing webapp tests)

- [x] @eins78 decide where settings and defaults should live

workflow: 
- open a draft PR, give update every 1-2 days
- as always, ask here if a task is unclear

### PR DESCRIPTION
**Pull request by michalpodlecki**
closes #170

API part is done, I had to fix an issue regarding vocabulary view permissions, I removed fields from DB, filtering by multilingual fields need to be fixed

### CODE REVIEW

**Comment by michalpodlecki** [comment]
@eins78 I added integration tests, regarding to the first requirement from the specs list I think it's covered by https://github.com/Madek/madek-webapp/blob/master/spec/features/app/language_switcher_spec.rb, am I right?

**Comment by eins78** [comment]
> @eins78 I added integration tests, regarding to the first requirement from the specs list I think it's covered by https://github.com/Madek/madek-webapp/blob/master/spec/features/app/language_switcher_spec.rb, am I right?

yes. and the functionality is only relevant in webapp, so it can stay there

**Comment by eins78** [comment]
spec fix: https://github.com/Madek/madek-api/commit/ce6ee670475b9917d70645ba4703bf977014c80b

**Comment by michalpodlecki** [comment]
@eins78 ready to proceed with :)

**Comment by michalpodlecki** [comment]
@eins78 https://ci.zhdk.ch/cider-ci/trees/03aa0b46f71582ad7b4dbf1a679c53cc45265c8a done!

**Pull request merged**
