### PR TITLE
feat: making a copy of media entry

### PR DESCRIPTION
**Pull request by michalpodlecki**
closes https://github.com/Madek/Madek/issues/269

### CODE REVIEW

**Review by eins78 — CHANGES_REQUESTED** [review]
there is a bug concerning the permissions when using the "Copy relations (parent collections & favorites)" option: the resulting MediaEntry is also added to Set the previous Entry is in, but the user does not have permissions.


steps to reproduce:
* upload MediaEntry *A* and publish
* log out, log in as phoettli
  * add Entry *A* to set "Sehenswerte Inhalte"
* log out, log in as yourself again
* replace MediaEntry *A*, using the "Copy Relations" feature, resulting in MediaEntry *B*
* result: MediaEntry *B* is now also contained in the Set "Sehenswerte Inhalte", even though my user would not have had permissions to add *A* or *B* to his Set

**Review by eins78 — COMMENTED** [review]
I still think the wording can be improved, but I will discuss this with @phoettli on basis of an RC that would include this feature.

**Comment by michalpodlecki** [comment]
I've fixed the bug, now a new media entry will be added only to accessible collections.

**Review by eins78 — APPROVED** [review]
sorry it took a bit longer. i confirm that the bug is fixed (i found another bug which confused me, but its already present on `stable`, will make a new issue for that)

**Pull request merged**
