### PR TITLE
webapp: feat: show sibling media entries from the same set(s)

### LINKED ISSUE #268: Zugang gleiches Set unter ähnliche Inhalte (show sibling entries from same set(s))
Title EN: **show sibling entries from same set(s) on top of “similar items"**

**Ausgangslage**
In der Detailansicht eines Medieneintrages sind weitere Medieneinträge aus dem selben Set nicht ersichtlich.

**Lösung**
Ein zusätzlicher Block einfügen vor dem Block "Nach ähnlichen Inhalten stöbern" mit den Medieneinträgen aus dem selben Set.
=> Falls Medieneintrag in mehreren Sets vorkommt, mehrere Reihen aufführen. Eine Reihe pro Set.

Siehe nachfolgende Skizze.

### PR DESCRIPTION
**Pull request by michalpodlecki**
Closes #268

### CODE REVIEW

**Review by eins78 — CHANGES_REQUESTED** [review]
Looks great in general, but there is a small cosmetic issue and also the performance is not great.

Visual detail: Please Link to the Set using the title as the target and remove the icon (that style more for subheading where there is no resource title present).

Screen Shot 2021-01-15 at 18 13 13

Performance: I have not looked at the logs, but just from a browser test this is rather slow. It could be inefficient queries, but I have a hunch its sadly a problem with our presenters when doing this kind of feature while using them "the right way" (composition and mapping leads to lots of overhead).
Please have a look if thats the problem or something else is slow and we can talk about possible solutions.

**Comment by michalpodlecki** [comment]
I've checked the set `Projektschaufenster Website ZHdK` and the performance is poor because of the amount of media entries it contains (>700). At the moment all of them are returned by request and rendered (sic!). If I compare it to `Browse similar items` section, it has limit up to 100 entries. Therefore the siblings from each collection can be limited as well as amount of data returned in response - only needed data.

**Comment by michalpodlecki** [comment]
I've limited props returned by presenters to needed only and here is what changed (based on https://test-blank.madek.zhdk.ch/entries/d9a3192b-c838-417e-b222-347020428443 Media Entry with 706 siblings from set mentioned above):
- size of the response decreased from 4.3MB to 165kB
- time needed to finish the request decreased from ~28s to ~7.5s

Further improvement would be to limit the amount of returned siblings, then the request should take less than 1s.

**Comment by eins78** [comment]
@michalpodlecki That looks very good already. I forgot to include the ID of my test case, but I had the tab still open and could see similar improvements: from 4MB/29sec to 0.28MB and 1.35sec.

Please also add limit of 100 entries like in the `browse` section, with that the performace should be sufficient.

**Comment by michalpodlecki** [comment]
The limit is already added 💪🏻

**Comment by michalpodlecki** [comment]
@eins78 do I have a green light to merge it in that form?

**Review by eins78 — APPROVED** [review]
😎

**Pull request merged**
