### PR TITLE
api: add missing sorting options for media-entries

### PR DESCRIPTION
**Pull request by michalpodlecki**
Media Entries can be now also ordered by:
- title ASC `?order=title_asc`
- title DESC `?order=title_desc`
- last_change `?order=last_change`

like in the webapp. Also when no `order` param is passed to API call but `collection_id` is, it takes sorting type from set's `sorting` db column.

closes https://github.com/Madek/madek/issues/205

### CODE REVIEW

**Review by eins78 — COMMENTED** [review]
Everything work as expected, very well!

Alas, the way it's implemented (and specified!) its a breaking change for the API. I'll need to decide with @DrTom on how to handle this before we can merge this.

**Comment by michalpodlecki** [comment]
In what case is it breaking the API?

**Comment by eins78** [comment]
> In what case is it breaking the API? Could you elaborate a bit?

* The `order` parameter already exists, but now the possible values and their behavior changed. Some requests that are now working will be yelding an error after this change.
* In the case of no `order` param but `collection_id` set, the order of the data might now change (because of the implicit application of the order saved in the collection display settings). While not as bad, it's still a data change and also might affect existing clients (especially sync jobs)

**Comment by michalpodlecki** [comment]
Mhmm, my first idea is to provide additional value for `order` param like "from_config" or similar. And then previous behaviour will be preserved.

**Comment by eins78** [comment]
> Mhmm, my first idea is to provide additional value for `order` param like "from_config" or similar. And then previous behaviour will be preserved.

That would be an option, but in this case we could also decide to do the change anyway (it's debatable if the changing the order when no param was given even _is_ a breaking change…).


> * The `order` parameter already exists, but now the possible values and their behavior changed. Some requests that are now working will be yielding an error after this change.

I just realized that I tested that in the wrong direction (new param in old API, not the other way around).
Actually, this is not an issue because the old values are still supported and work as before (and are even [tested](https://github.com/Madek/madek-api/compare/e56bff871ee41c147c5eb57ba1c7a45598808c46...b87689be2943b95b3cdfe967c91b54a4280aa7a4#diff-71480e55e0e5cb565f0f80c8f38dab7cR18) 👍 ). So this is just a matter of documentation.

**Review by eins78 — APPROVED** [review]
please add the docs changes from this commit, then its good to go!
https://github.com/Madek/madek-api/commit/8c4e22658c932cf7dda7ee0d006c89e849d263d1

**Review by eins78 — CHANGES_REQUESTED** [review]
per our discussion: with the upcoming change to also support "manual set sorting" mode, which then may be or not be the "saved display mode", the implicit handling of the empty `order` param gets confusing very quickly. as a bonus point there won't be *any* changes to current clients and it more future-proof. 

- [x] restore old default for empty `order` param (always `desc`)
- [x] apply "saved display mode" when value is `collection_display_settings` (or propose a better name…)
    - [ ] throw error if `order=collection_display_settings` and no `collection_id`

**Comment by michalpodlecki** [comment]
The second change will be a part of another PR. I will reference to it once I create it.

**Comment by michalpodlecki** [comment]
@eins78 the previous default sorting was set to ascending one so I restored it to this value. Also I've added `stored_in_collection` as a possible value to `order` param as you suggested recently.

**Review by eins78 — CHANGES_REQUESTED** [review]
Works ok and is well tested. Implementation is straightforward, but its missing some error handling for invalid params. 

Have a look how it's done here, in case of invalid uuid:
https://github.com/Madek/madek-api/blob/master/src/madek/api/resources.clj#L74-L77


1. when `order` param is unknown 
- [ ] Error 422
- see <https://test.madek.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-entries%2F%3Fcollection_id%3De2f526f7-67f9-4533-b2dd-08c2c81ad8a0%26order%3Dxzy&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A>

2. when `stored_in_collection` and no `colection_id`
- [x] adjust message `"only the following values are allowed as order parameter: desc, asc, title_asc, title_desc, last_change, stored_in_collection"` 
- [ ] Error 422 
- see <https://test.madek.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-entries%2F%3Forder%3Dstored_in_collection&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A>

**Comment by michalpodlecki** [comment]
@eins78 the recent changes to API https://github.com/Madek/madek-api/commit/8f976310282410e9a250b447cb307cfcb6240de8

**Review by eins78 — APPROVED** [review]
😎

**Pull request merged**
