### PR TITLE
webapp: feat: add responsible delegation filter

### LINKED ISSUE #281: Enhance filter section for Delegation
add separate section for delegation
image

### PR DESCRIPTION
**Pull request by michalpodlecki**
Closes #281 

This PR https://github.com/Madek/madek/pull/309 has to merged first.

### CODE REVIEW

**Comment by eins78** [comment]
@michalpodlecki please rebase

**Comment by michalpodlecki** [comment]
ok, in progress...

**Comment by michalpodlecki** [comment]
@eins78 rebased

**Comment by michalpodlecki** [comment]
@eins78 rebased

**Review by eins78 — APPROVED** [review]
:shipit:

**Pull request merged**
