### PR TITLE
feat: add static pages

### PR DESCRIPTION
**Pull request by michalpodlecki**
closes https://github.com/Madek/madek/issues/285

### CODE REVIEW

**Review by eins78 — CHANGES_REQUESTED** [review]
Generally works as expected, but there is a edge case with the localization:
Its currently possible to create a page and not fill out the default language – then the respective page crashes by default. 
I see two solutions, not sure which is better but I lean towards 1 because its simpler:
1. require content for default language (will still break when default lang is ever changed, but so will other stuff presumably)
2. use a different fallback mechanism for the languages (try the locale, then the default locale, then every other locale)

**Comment by michalpodlecki** [comment]
Oh you're right, I forgot to add a db constraint which will take care of that.

**Comment by michalpodlecki** [comment]
@eins78 I've added the db "constraint"/trigger checking presence of value for default locale according to the actual default locale from `app_settings` table.

**Comment by eins78** [comment]
@michalpodlecki two more small things:
* admin: make the `<textarea required` for the default language, so the browser already enforces it before the DB trigger complains
* webapp: add the ([`titleize`d](https://apidock.com/rails/String/titleize)) version of the page name as the title. in the view something like:
    ```ruby
    content_for(:title_head) { @page.name.titleize }
    ```

**Comment by michalpodlecki** [comment]
@eins78 updated according to your comment

**Review by eins78 — APPROVED** [review]

**Pull request merged**
