### PR TITLE
feat: multilingual labels & descriptions for vocabularies & contexts

### LINKED ISSUE #163: Translation for Vocabulary and Context
- like the previous work regarding MetaKeys (https://github.com/Madek/madek/commit/bef86c7fe30dac507d19303eaacecb81ecee21a9)

- [x] extend DB (tables `vocabularies`, `contexts`; fields `label`, `description`)
- [x] Admin UI
- [x] Webapp
  - To be defined further, but "everywhere"
- [x] API

General Question, since those are the last tables on the translation roadmap:
How do we want to handle the old, non translated fields (e.g. `label`). 
Right now it contains the translation into the default lang, which can change.
Maybe there is a plan that I am not aware of – then we should document it. 
We could update the fields with triggers in case the default lang changes, but I am leaning towards removing the fields and adapting all the Apps to not use them anymore (the usage is obsolete in almost all cases anyhow, the only important place is the API where the field should still be supported (but it obv. does not need to a DB field to do that).

### PR DESCRIPTION
**Pull request by michalpodlecki**
closes #163

### CODE REVIEW

**Comment by eins78** [comment]
@michalpodlecki It seems to me there are 2 tests which are failing (hard to see atm because of the ci flakyness…). Regarding the scope of the spec it is plausible that they need to be adapted. Could you have a look please?
https://ci.zhdk.ch/cider-ci/ui/workspace/tasks/44c41ca2-2ed1-5c81-9e77-a4be4671a2f9
https://ci.zhdk.ch/cider-ci/ui/workspace/tasks/8f1c50e7-0ca6-52e3-94eb-7e9b1176f489

**Comment by michalpodlecki** [comment]
@eins78 fixed! sorry for my oversight

**Comment by nimaai** [comment]
@michalpodlecki Maybe if you could rename the local variable `settings` to something else, eg. `locales` at this place: https://github.com/Madek/madek-api/compare/9d1dad893d147ba12cf800c7548b1d57a0e0bd86...e2c6dc52429eacb04d69e9923c868e79d0076f59#diff-9d2ab20cf67ba66732618ec1d993acdcR26

**Comment by michalpodlecki** [comment]
@eins78 I adjusted specs and applied changed requested by @nimaai

**Pull request merged**
