### PR TITLE
Roles for Persons

### PR DESCRIPTION
**Pull request by michalpodlecki**
Actual progress of the feature

Project details: https://github.com/Madek/madek/projects/7

### CODE REVIEW

**Comment by eins78** [comment]
- [ ] should work for people pages (maybe filter adjustment needed only) @michalpodlecki 
- [ ] api docs access for MP @eins78

**Comment by eins78** [comment]
tasks:

- [ ] remove demo data from DB/seeds/etc
- [ ] scope roles by meta_key

new dummy data:

```yaml
meta_keys:
  - id: "test:roles_music"
    labels:
      en: "Roles (Music)"

  - id: "test:roles_movie"
    labels:
      en: "Roles (Movie)"

roles:
  - id: a1
    meta_key_id: 
    labels: "test:roles_music"
      en: "Producer"
  - id: a2
    meta_key_id: 
    labels: "test:roles_music"
      en: "Writer"
  - id: a3
    meta_key_id: 
    labels: "test:roles_music"
      en: "Singer"
  - id: b1
    meta_key_id: 
    labels: "test:roles_movie"
      en: "Producer"
  - id: b2
    meta_key_id: 
    labels: "test:roles_movie"
      en: "Writer"
  - id: b3
    meta_key_id: 
    labels: "test:roles_movie"
      en: "Actor"
```

**Comment by eins78** [comment]
test results:

---

Error: Cant have duplicate names for diff. metakeys – constraint should be specific to a single metakey

- create metakey of type roles `test:a`
- create Metakey of type roles `test:b`
- create Role for `test:a` with label.de = "Produzent"
- create Role for `test:b` with label.de = "Produzent"
- ```
  An error occured code: 500
  Message:
  org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "index_roles_on_labels" Detail: Key (labels)=("de"=>"Produzent", "en"=>"Producer") already exists.
  ```

---

**Comment by michalpodlecki** [comment]
Fixed https://github.com/Madek/madek/commit/97e859e442c0a0882458d7330029f0b063bdf345

**Comment by eins78** [comment]
rest of the tests were successful, looking good so far. i will still test the latest fix, its deploying atm.

**Comment by eins78** [comment]
Test fail:
Presenter/View should never return/show empty List of values.
Example Entry: [UI](https://madek-spiel.kiste.li/entries/cd8da308-f475-4c78-bf50-b45bc2e05613),  [YAML](https://madek-spiel.kiste.li/entries/cd8da308-f475-4c78-bf50-b45bc2e05613.yaml)

UI should not show "Rollen (Film)" without Roles, underlying Problem is the data from presenter (or models), it should not have:

```yaml
- media_entry_id: cd8da308-f475-4c78-bf50-b45bc2e05613
      values: []
      meta_key_id: people:roles_movie
      type: MetaDatum::Roles
…
```

**Comment by eins78** [comment]
Test OK:
- div. context configs
- people pages
- filter in search

**Comment by eins78** [comment]
db schema: found 3 missing constraints

- [ ] fkeys, not null for meta_key and creator
    ```sql
    ALTER TABLE "public"."roles"
      ADD FOREIGN KEY ("meta_key_id") REFERENCES "public"."meta_keys"("id"),
      ADD FOREIGN KEY ("creator_id") REFERENCES "public"."users"("id"),
      ALTER COLUMN "creator_id" SET NOT NULL;
   ```
- [ ] at least one of the labels in the labels hstore must be non-blank.

**Comment by eins78** [comment]
@michalpodlecki FYI i did a simple csv import https://github.com/Madek/madek_admin-webapp/commit/8d6a647312da3045add33c9c47eafadb7e28cb64
thats how i found the missing db constraints, now i am quite sure that we're done after those :)

**Comment by michalpodlecki** [comment]
@eins78 Fixed, also I found hardcoded strings, I extracted them to translations file, please update the german versions :)
https://github.com/Madek/madek/pull/137/commits/e7ac1a8a6c471cc7b4147da952c63a034650d5d0

**Comment by eins78** [comment]
Test result: Everything works as expected now!

**Comment by eins78** [comment]
@michalpodlecki I added a "this is not stable" warning to the API docs as mentioned, also rebased and squashed some things. I consider it done for now, but before merging to master you might want to have one last look (sanity check)
https://github.com/Madek/madek/tree/feat/roles

**Comment by michalpodlecki** [comment]
@eins78 I looked through and it looks like a masterpiece 🥇

**Comment by eins78** [comment]
also "fixed" flay, no hopefully mergeable https://github.com/Madek/madek-datalayer/commit/07c8c8861cca55a2cd4bdd8f0d19a2edfc8444ab

**Pull request merged**
